language: node_js
node_js:
- node
script: npm test && npm run-script build
deploy:
  provider: s3
  access_key_id: AKIAIXLGL5XSBNB3EVOA
  secret_access_key:
    secure: lucAYt+kRoAUM1Ttn7nRAXqDJNUdA2sh3vKZSGI+GbRgPCpb9DORhpZTpz7cEjAg6qZCfHbk6SQS84I8FY8emfH5dpdIT0kfPo+sgFfnon2SFOqbef1Tzlr+L3dOCNqPyVsPn3LppwRioRcm+0siQaZRmf6xnbgMWCxV8k8u5Bg1roje4bOeqBiJ7pJ6VGBAnKydCYE1ade5RDgI0PMQznfi4IUi3T+9FkyHkRsJ183Lwumm5RjO2MPbPS97JYsufyZm3FiC3KFCIotJqpCn2aGboxvHFpW+19YtQR6E6pyxKH1JUpop+Ix+sRunC0XcnoxDyyjHakUGOoPLox0MWiB7/RcljgKZmF5xD7pmyR1gU0qIHdTPKpu58OD2TELIk+23o3dW7ALzPZtwiAk1RQJArh7JzuAcQYRBagZHCTdUSrMaE+eIqwhL3oTi6t4AK6hEXy0FkJuPCy0Vd0AZ8aNKsz8RDHXdMNywG1pZuDNJhQ2SDGmsxZhXHoFug+wJUai8gpjF5qMBFMVJPorjvkIO5z86poWbxsh+5CarHlqyF+z1dVb0Pq7Q4jNeM3kOogT2zZpuSauGnnU5ClU4hVcvmPz3z5tIGhxXuxg9QT9wu8tcEDzna5xNqvGNP2Tipxjb1jvRoOeyUNOGaQgFfmt7xyDRx8F6nJuG6RWrbbw=
  bucket: six-of-spades.markbiesheuvel.nl
  skip_cleanup: true
  local-dir: out
  acl: public_read
  on:
    repo: MarkBiesheuvel/six-of-spades